# #ddev-generated
# Install Ruby and dependencies for serverspec
RUN sudo apt-get update && \
    sudo apt-get install -y ruby-full build-essential && \
    sudo gem install bundler serverspec rake rspec highline net-ssh ed25519 bcrypt_pbkdf
