#ddev-generated
services:
  serverspec:
    container_name: ddev-${DDEV_SITENAME}-serverspec
    image: ${SERVERSPEC_DOCKER_IMAGE:-ddev/ddev-utilities:latest}
    command: tail -f /dev/null
    restart: "no"
    # These labels ensure this service is discoverable by DDEV.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}

    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
